version: '3.9'


services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - /Users/itbuddy/Docker/Container-data/mysql/var/lib/mysql:/var/lib/mysql
      - /Users/itbuddy/Docker/Container-data/mysql/etc/mysql/conf.d:/etc/mysql/conf.d
      
